# Generated by Django 4.2.3 on 2023-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChainServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='local', max_length=100, verbose_name='Server Name')),
            ],
        ),
    ]
