# Generated by Django 4.2.3 on 2023-08-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainserver',
            options={'verbose_name': 'BlockChainServer', 'verbose_name_plural': 'BlockChainServers'},
        ),
    ]
