# Generated by Django 4.2.3 on 2023-08-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
