# Generated by Django 4.2.3 on 2023-07-29 04:06

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[config.helpers.validate_amount], verbose_name='Amount of approve'),
        ),
    ]
