# Generated by Django 4.2.3 on 2023-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_alter_transfer_blockchain_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='token_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Token name'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='token_symbol',
            field=models.CharField(max_length=50, null=True, verbose_name='Token symbol'),
        ),
    ]
