# Generated by Django 4.2.3 on 2023-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_blockchain_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='blockchain_server',
            field=models.CharField(max_length=50, null=True, verbose_name='Blockchain server'),
        ),
    ]
